"""empty message

Revision ID: 8a528456fbf4
Revises: a5c5aaafabbe
Create Date: 2025-12-31 10:43:39.863449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8a528456fbf4'
down_revision: Union[str, None] = 'a5c5aaafabbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if eventtype enum exists, create if it doesn't (using DO block to avoid errors)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE eventtype AS ENUM ('Food', 'Litter', 'Medicine');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Use postgresql.ENUM with create_type=False to prevent SQLAlchemy from trying to create it
    eventtype_enum = postgresql.ENUM('Food', 'Litter', 'Medicine', name='eventtype', create_type=False)
    
    op.create_table('saved_event',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('household_uuid', sa.String(length=64), nullable=False),
    sa.Column('pet_uuid', sa.String(length=64), nullable=True),
    sa.Column('type', eventtype_enum, nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['household_uuid'], ['household.uuid'], ),
    sa.ForeignKeyConstraint(['pet_uuid'], ['pet.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_saved_event_type'), 'saved_event', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_event_type'), table_name='saved_event')
    op.drop_table('saved_event')
    # ### end Alembic commands ###

