"""empty message

Revision ID: c6c00ddb26c9
Revises: add_vitals_enum
Create Date: 2026-01-03 09:30:03.186859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6c00ddb26c9'
down_revision: Union[str, None] = 'add_vitals_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_event',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', postgresql.ENUM(name='foodtype', create_type=False), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('unit', postgresql.ENUM(name='unit', create_type=False), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('medicine_event',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('vitals_event',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Weight', 'Length', name='vitalstype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_column('event', 'meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('vitals_event')
    op.drop_table('medicine_event')
    op.drop_table('food_event')
    # ### end Alembic commands ###

